import recoveredGuides from "./recovered-guides.json";

export const SITE_URL = "https://pawandwhisker.net";
export const SUBSCRIPTION_PRICE = "$4.99/month";
export const STRIPE_PAYMENT_LINK = "https://buy.stripe.com/3cI6oG32021Bedm1Xkgw002";

export type SitePage = {
  path: string;
  title: string;
  heading: string;
  description: string;
  html?: string;
  kind?: string;
  noindex?: boolean;
};

const contact = '<a href="mailto:paul@pawandwhisker.net">paul@pawandwhisker.net</a>';
const medical = `<p>Paw &amp; Whisker provides general pet information, not veterinary advice, diagnosis or treatment. AI can make mistakes. It never replaces a licensed veterinarian.</p><p>If your pet has trouble breathing, collapses, has seizures, is bleeding heavily, may have eaten poison, or has other urgent signs, go to an emergency vet immediately. Do not wait for an AI response.</p>`;

export const pages: SitePage[] = [
  { path: "/", title: "Free Puppy Care Help & AI Pet Chat | Paw & Whisker", heading: "Free puppy care help", description: "Start with free puppy guides, two free AI pet questions and a free symptom check. Get general pet information for your puppy's first days at home." },
  { path: "/guides", title: "Free Puppy Care Guides & Checklists | Paw & Whisker", heading: "Free guides for your puppy's first days", description: "Read our new puppy checklist, first 30 days plan and toxic foods guide. Practical, free information to help you prepare for life with your puppy.", kind: "guides" },
  ...recoveredGuides,
  { path: "/pricing", title: "Free Pet Chat & Subscription Pricing | Paw & Whisker", heading: "Start free. Upgrade only if you want to.", description: "Try your first two AI pet questions free, browse free puppy guides or take the free symptom check. The optional paid plan is $4.99 per month.", kind: "pricing",
    html: `<h2>Free to start</h2><ul><li>Your first two questions in the AI chat are free.</li><li>Our puppy guides are free to read.</li><li>The symptom check is free.</li></ul><p><a class="content-button" href="/#free-chat">Try the free AI chat</a> <a href="https://quiz.pawandwhisker.net">Take the free symptom check →</a></p><h2>Optional subscription: ${SUBSCRIPTION_PRICE}</h2><p>The app's advertised monthly plan includes unlimited questions and image analysis. Subscriptions are billed through Stripe and can be cancelled anytime. Cancellation stops future renewals; request a refund within 7 days of a charge.</p><p><a class="content-secondary" href="${STRIPE_PAYMENT_LINK}">See the paid plan on Stripe →</a></p><h2>Puppy Survival Kit</h2><p>The printable Puppy Survival Kit is a separate, one-time purchase, not included in the chat subscription. <a href="https://pawandwhisker.net/puppy-kit/">Explore the Puppy Kit</a>.</p>${medical}` },
  { path: "/puppy-kit/", title: "New Puppy Survival Kit: 7 Printable Guides | Paw & Whisker", heading: "The New Puppy Survival Kit", description: "A printable plan for your puppy's first 30 days: schedule, shopping checklist, housetraining tracker, health record and emergency sheet. One-time $12.", kind: "kit",
    html: `<p>Bringing a puppy home is wonderful — and can feel overwhelming. This kit is a print-it-and-stick-it-on-the-fridge plan for your first 30 days.</p><h2>What's inside — 7 printable PDFs</h2><ul><li><strong>First 30 Days Schedule:</strong> settling in, routine building, socialization and alone-time training.</li><li><strong>Complete Shopping Checklist:</strong> what to buy, what to skip and a first-year budget.</li><li><strong>Housetraining Tracker:</strong> a method and weekly tracking grid.</li><li><strong>Puppy Health Record Book:</strong> vaccines, deworming, weight and vet visits.</li><li><strong>12 Treat Recipes:</strong> no-bake and baked treats, including a xylitol warning.</li><li><strong>Fridge Emergency Sheet:</strong> toxic foods, urgent signs and poison-control numbers.</li><li><strong>The 2AM Cheat Sheet:</strong> information for late-night puppy questions.</li></ul><p>One-time purchase: $12. This is separate from the monthly AI chat subscription.</p><p><a class="content-button" href="https://buy.stripe.com/8x2bJ0eKI0Xx0mwatQgw008">Get the Puppy Kit on Stripe →</a></p><p>This page and checkout link were recovered from the existing live Puppy Kit page. For delivery questions, contact ${contact}.</p>${medical}` },
  { path: "/privacy", title: "Privacy Policy Draft | Paw & Whisker", heading: "Privacy policy", description: "Learn what Paw & Whisker collects, how chat and pet information is used, and how to request a data export or deletion. Plain-English privacy draft.", kind: "legal",
    html: `<p class="draft-notice">Plain-English draft — review before launch. These are our intended commitments; confirm security and retention practices before publishing.</p><h2>What we collect</h2><p>We collect the questions and photos you submit, information you choose to share about your pet, conversation records and an email address if you provide one. Browser storage remembers session identifiers, pet preferences and chat state. We also record usage events such as chat and checkout interactions to understand how the service is used.</p><h2>How information is used</h2><p>We use this information to respond to you, remember conversations, provide service support and improve the service. Chat content and uploaded images are sent to our AI service provider to generate responses. Hosting, AI and payment providers process the information needed to provide their services. Do not submit unnecessary personal or sensitive information.</p><h2>Security and storage</h2><p>We store data securely and use reasonable safeguards designed to protect it. No online service can promise perfect security. Conversations and account-related information may be stored so the service can operate; exact retention periods need to be confirmed before this draft is published.</p><h2>Your choices</h2><p>You can request an export or deletion of your data by emailing ${contact}. Include enough information to identify the relevant records, but do not send passwords or payment card numbers. We may need to verify your request. Some records may need to be retained for legal or payment obligations. Clearing browser storage removes local preferences, but does not delete server-side records.</p><h2>Payments</h2><p>Stripe processes subscription payments. Do not put payment details in chat. Stripe's own privacy terms apply to the information it handles.</p><h2>Questions or changes</h2><p>Contact ${contact} with privacy questions. We will update this page when our practices change.</p>` },
  { path: "/terms", title: "Terms of Service Draft | Paw & Whisker", heading: "Terms of service", description: "Plain-English terms for Paw & Whisker: educational pet information, responsible use, Stripe billing, cancellation and refunds within seven days.", kind: "legal",
    html: `<p class="draft-notice">Plain-English draft — review before launch.</p><h2>What this service does</h2>${medical}<h2>Use the service responsibly</h2><p>Use it for general pet information and everyday questions. Do not rely on it for emergencies, medication doses, diagnosis or treatment decisions. Do not submit unlawful content or information you do not have permission to share.</p><h2>Subscriptions and payments</h2><p>The currently advertised subscription is ${SUBSCRIPTION_PRICE}. Stripe handles billing. Subscriptions renew monthly until cancelled. You can cancel anytime through the Stripe subscription-management link if provided, or contact ${contact} for cancellation help. Cancellation stops future renewals; it does not automatically refund past charges.</p><h2>Refunds</h2><p>Request a refund within 7 days of a charge by emailing ${contact}. See our <a href="/refund">refund policy</a>. Your statutory consumer rights are not limited by this policy.</p><h2>Service limitations</h2><p>AI answers may be incomplete or wrong, and service availability is not guaranteed. You remain responsible for decisions about your pet. Nothing here excludes rights or liabilities that cannot legally be excluded.</p><h2>Contact</h2><p>Questions about these terms? Email ${contact}.</p>` },
  { path: "/refund", title: "7-Day Refund Policy Draft | Paw & Whisker", heading: "Refund and cancellation policy", description: "Request a Paw & Whisker refund within 7 days of a charge. Learn how to cancel a Stripe-billed subscription and contact us for billing help.", kind: "legal",
    html: `<p class="draft-notice">Plain-English draft — review before launch.</p><h2>7-day refund window</h2><p>You may request a refund within 7 days of a charge. Email ${contact} with the email used at checkout, the charge date and, if available, your Stripe receipt reference. Do not send card numbers. We will review the request and arrange an eligible refund through Stripe to the original payment method. Bank processing times vary.</p><h2>Cancel anytime</h2><p>Subscriptions are billed through Stripe. Cancel using the subscription-management link if supplied, or email us for help. Cancellation stops future renewals. If you also want a refund for a recent charge, please request it within the 7-day window.</p><h2>Problems with a charge or delivery?</h2><p>Contact us if you believe a charge is incorrect or a purchased download has not arrived. This policy does not remove any refund or cancellation rights you have under applicable law.</p>` },
  { path: "/medical-disclaimer", title: "Medical Disclaimer: Not Veterinary Advice | Paw & Whisker", heading: "Medical disclaimer", description: "Paw & Whisker offers general pet information, not veterinary advice. AI never replaces a vet. Seek an emergency veterinarian for urgent signs.", kind: "legal",
    html: `<p class="draft-notice">Plain-English draft — review before launch.</p><h2>Information, not veterinary care</h2>${medical}<h2>No veterinary review</h2><p>The service and AI answers are not currently reviewed by a veterinarian. Guides and symptom checks are educational resources, not a clinical assessment. No veterinarian-client-patient relationship is created by using the site.</p><h2>When to seek help</h2><p>Contact your own vet for symptoms, persistent changes, vaccination and medication questions. For suspected poisoning, contact an emergency vet or an animal poison-control service immediately. Never give medication, induce vomiting or change prescribed treatment based only on this site.</p><h2>AI has limits</h2><p>An AI cannot examine your pet, perform tests or reliably interpret every photo. Responses may be inaccurate or miss important details. A reassuring answer does not mean your pet is safe.</p>` },
  { path: "/chat", title: "Your Private AI Pet Chat | Paw & Whisker", heading: "Pet chat", description: "Ask general pet-care questions in your Paw & Whisker chat. AI information is not veterinary advice. Contact an emergency vet for urgent signs.", noindex: true },
  { path: "/success", title: "Subscription Next Steps | Paw & Whisker", heading: "Subscription next steps", description: "Continue to your Paw & Whisker pet chat and find support after checkout. For billing or cancellation questions, contact Paw & Whisker support.", noindex: true },
  { path: "/admin/analytics", title: "Private Analytics Dashboard | Paw & Whisker", heading: "Analytics", description: "Private Paw & Whisker analytics dashboard for authorized administrators. This page is not intended for public search results.", noindex: true },
];

export const notFoundPage: SitePage = { path: "/404", title: "Page Not Found | Paw & Whisker", heading: "We couldn't find that page", description: "This page may have moved or no longer exist. Find free puppy guides and general pet-care help on Paw & Whisker.", noindex: true, kind: "404" };

export function normalizePath(path: string) {
  const withoutSlash = path.replace(/\/+$/, "") || "/";
  return withoutSlash === "/puppy-kit" ? "/puppy-kit/" : withoutSlash;
}

export function getPage(path: string): SitePage {
  return pages.find(page => page.path === normalizePath(path)) ?? { ...notFoundPage, path };
}

export const guideRedirects = Object.fromEntries(recoveredGuides.map(page => [page.path + ".html", page.path]));